#!/usr/bin/env node
/**
 * Relayer Setup Script
 * 
 * Guides user through:
 * 1. Configuring environment variables
 * 2. Granting minting permissions
 * 3. Verifying setup
 */

import { generateWallet } from '@stacks/wallet-sdk';
import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('═══════════════════════════════════════════════════════════');
  console.log('         RELAYER SETUP WIZARD');
  console.log('═══════════════════════════════════════════════════════════');
  console.log('');
  
  const config = {};
  
  // Step 1: Sepolia RPC
  console.log('STEP 1: Sepolia RPC Configuration');
  console.log('─────────────────────────────────────────────────────────────');
  const sepoliaRpc = await question('Enter Sepolia RPC URL (or press Enter for public): ');
  config.SEPOLIA_RPC = sepoliaRpc || 'https://rpc.sepolia.org';
  console.log(`✅ Using: ${config.SEPOLIA_RPC}`);
  console.log('');
  
  // Step 2: Sepolia Contract Address
  console.log('STEP 2: Sepolia Contract Address');
  console.log('─────────────────────────────────────────────────────────────');
  const contractAddress = await question('Enter PaymentReceiver contract address: ');
  if (!contractAddress || !contractAddress.startsWith('0x')) {
    console.log('⚠️  Invalid address. You can set this later in .env');
    config.SEPOLIA_CONTRACT = '';
  } else {
    config.SEPOLIA_CONTRACT = contractAddress;
    console.log(`✅ Contract: ${config.SEPOLIA_CONTRACT}`);
  }
  console.log('');
  
  // Step 3: Relayer Mnemonic
  console.log('STEP 3: Relayer Wallet');
  console.log('─────────────────────────────────────────────────────────────');
  console.log('The relayer needs a wallet with minting permissions.');
  const useExisting = await question('Use existing mnemonic? (y/n): ');
  
  if (useExisting.toLowerCase() === 'y') {
    const mnemonic = await question('Enter 12-word mnemonic: ');
    config.RELAYER_MNEMONIC = mnemonic;
    
    // Derive address
    const wallet = await generateWallet({ secretKey: mnemonic, password: '' });
    const address = wallet.accounts[0].stxPrivateKey;
    console.log(`✅ Relayer address derived`);
  } else {
    console.log('⚠️  You need to set RELAYER_MNEMONIC in .env manually');
    config.RELAYER_MNEMONIC = '';
  }
  console.log('');
  
  // Step 4: Generate .env file
  console.log('STEP 4: Generating .env file');
  console.log('─────────────────────────────────────────────────────────────');
  
  const envContent = `# Relayer Configuration
# Generated by setup script

SEPOLIA_RPC=${config.SEPOLIA_RPC}
SEPOLIA_CONTRACT=${config.SEPOLIA_CONTRACT}
RELAYER_MNEMONIC=${config.RELAYER_MNEMONIC}

# Stacks Configuration
STACKS_DEPLOYER=ST2N6HZJPPQ8VGJZGPPP8754CFNGWKBHVAZ85QB6K
`;
  
  const envPath = path.join(__dirname, '../.env');
  fs.writeFileSync(envPath, envContent);
  console.log(`✅ Created .env file at: ${envPath}`);
  console.log('');
  
  // Step 5: Next steps
  console.log('═══════════════════════════════════════════════════════════');
  console.log('                    SETUP COMPLETE');
  console.log('═══════════════════════════════════════════════════════════');
  console.log('');
  console.log('Next steps:');
  console.log('');
  console.log('1. Grant minting permissions:');
  console.log('   Call on Stacks: token-usdh-v2.add-minter(relayer-address)');
  console.log('');
  console.log('2. Test Chainlink connection:');
  console.log('   node src/test-chainlink.js');
  console.log('');
  console.log('3. Start relayer:');
  console.log('   npm start');
  console.log('');
  
  rl.close();
}

setup().catch(console.error);


